-- Small, attributed starter directory. No copyrighted standard clauses, product specs or claimed current editions.

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('f5628ebe-343a-5b32-abab-7f92e64913e9','IEC 60364 — Low-voltage electrical installations (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60364','IEC 60364','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60364: Low-voltage electrical installations. Installation design and protection family; related European HD 60364 parts and Estonian EVS adoptions must be checked separately.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','44e7cb8f0df6c7d3f37b5ad4acbd84cb6a72d4f68135c4289d3051f7e600353e','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('beb472ce-bd2d-5bc5-93ea-a163bd1203df','f5628ebe-343a-5b32-abab-7f92e64913e9','Scope metadata','Scope metadata',0,'IEC 60364: Low-voltage electrical installations. Installation design and protection family; related European HD 60364 parts and Estonian EVS adoptions must be checked separately.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',138,setweight(to_tsvector('simple','IEC 60364 — Low-voltage electrical installations (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60364: Low-voltage electrical installations. Installation design and protection family; related European HD 60364 parts and Estonian EVS adoptions must be checked separately.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('2de8563a-32bb-5fa4-8738-e143c9b43c0c','IEC 60898-1 — Circuit breakers for household and similar installations (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60898-1','IEC 60898','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60898-1: Circuit breakers for household and similar installations. Household and similar circuit-breaker family, including AC MCB characteristics. Distinguish Icn from industrial Icu/Ics ratings.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','4fd0050445da09108127e0cd674d120153388d4d74f5d78342be86aecbd60681','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('17bdccc1-99f4-546f-b714-528616a264a3','2de8563a-32bb-5fa4-8738-e143c9b43c0c','Scope metadata','Scope metadata',0,'IEC 60898-1: Circuit breakers for household and similar installations. Household and similar circuit-breaker family, including AC MCB characteristics. Distinguish Icn from industrial Icu/Ics ratings.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',145,setweight(to_tsvector('simple','IEC 60898-1 — Circuit breakers for household and similar installations (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60898-1: Circuit breakers for household and similar installations. Household and similar circuit-breaker family, including AC MCB characteristics. Distinguish Icn from industrial Icu/Ics ratings.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('1aec3f0b-6e1b-54fc-ada0-e7f5a243afd6','IEC 60947 — Low-voltage switchgear and controlgear (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60947','IEC 60947','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60947: Low-voltage switchgear and controlgear. Switchgear/controlgear family. Parts define different product categories; use the applicable part and edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','d8f4ac92345afee2445a6c91f3345ad3482bcdb5fb6531143420d3b345d3f3e7','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('1cc9962c-1d57-576a-bc7b-9f7e5a47cf9c','1aec3f0b-6e1b-54fc-ada0-e7f5a243afd6','Scope metadata','Scope metadata',0,'IEC 60947: Low-voltage switchgear and controlgear. Switchgear/controlgear family. Parts define different product categories; use the applicable part and edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',132,setweight(to_tsvector('simple','IEC 60947 — Low-voltage switchgear and controlgear (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60947: Low-voltage switchgear and controlgear. Switchgear/controlgear family. Parts define different product categories; use the applicable part and edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('69022b8e-c7f5-5e00-b13e-c6c71a8c7104','IEC 60947-2 — Circuit breakers (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60947-2','IEC 60947','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60947-2: Circuit breakers. Industrial circuit breakers; Icu and Ics breaking-capacity terminology. Actual requirements and application conditions require the licensed edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','794f6d473fd660b781680cfaec184b6b411246dbebb3d2ab43c52b849cd8d5c2','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('54e1e1d8-03e6-5d51-8181-40f07a98281e','69022b8e-c7f5-5e00-b13e-c6c71a8c7104','Scope metadata','Scope metadata',0,'IEC 60947-2: Circuit breakers. Industrial circuit breakers; Icu and Ics breaking-capacity terminology. Actual requirements and application conditions require the licensed edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',138,setweight(to_tsvector('simple','IEC 60947-2 — Circuit breakers (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60947-2: Circuit breakers. Industrial circuit breakers; Icu and Ics breaking-capacity terminology. Actual requirements and application conditions require the licensed edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('4e861aff-2840-56f3-ab0c-3da080176350','IEC 60947-4-1 — Contactors and motor starters (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60947-4-1','IEC 60947','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60947-4-1: Contactors and motor starters. Contactors, motor starters, utilization categories and coordination. Use manufacturer coordination tables for the exact motor starter combination.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','fc280a7e3c0b7166516378540c20ab7135067ca30ec364fa3038400d9d1e191f','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('cd0f578e-82bc-56f1-b214-82b52693efef','4e861aff-2840-56f3-ab0c-3da080176350','Scope metadata','Scope metadata',0,'IEC 60947-4-1: Contactors and motor starters. Contactors, motor starters, utilization categories and coordination. Use manufacturer coordination tables for the exact motor starter combination.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',143,setweight(to_tsvector('simple','IEC 60947-4-1 — Contactors and motor starters (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60947-4-1: Contactors and motor starters. Contactors, motor starters, utilization categories and coordination. Use manufacturer coordination tables for the exact motor starter combination.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('ac2ea4ad-57d0-579c-8f35-5f1c8b1d0837','IEC 61008 — RCCBs (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 61008','IEC 61008','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 61008: RCCBs. Residual-current circuit breakers without integral overcurrent protection. An RCCB does not replace separate overload/short-circuit protection.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','850076de08804904ad74b0f27bd5f7575ec0ab7d973d996dd86fba3ae2264b9d','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('3e963723-00d5-5857-80d7-c9581c7eac25','ac2ea4ad-57d0-579c-8f35-5f1c8b1d0837','Scope metadata','Scope metadata',0,'IEC 61008: RCCBs. Residual-current circuit breakers without integral overcurrent protection. An RCCB does not replace separate overload/short-circuit protection.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',132,setweight(to_tsvector('simple','IEC 61008 — RCCBs (family/scope metadata)'),'A') || to_tsvector('simple','IEC 61008: RCCBs. Residual-current circuit breakers without integral overcurrent protection. An RCCB does not replace separate overload/short-circuit protection.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('c584a1e5-cd02-51be-bd14-6d717021c0de','IEC 61009 — RCBOs (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 61009','IEC 61009','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 61009: RCBOs. Residual-current circuit breakers incorporating overcurrent protection; distinguish from RCCBs.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','8010cbc8a2e499911ca053022f2b2e79cc2c2ac6e77da2ad6c49b3893c583e65','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('114d98ac-7a8e-5ec0-a308-a8b47bbb879b','c584a1e5-cd02-51be-bd14-6d717021c0de','Scope metadata','Scope metadata',0,'IEC 61009: RCBOs. Residual-current circuit breakers incorporating overcurrent protection; distinguish from RCCBs.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',116,setweight(to_tsvector('simple','IEC 61009 — RCBOs (family/scope metadata)'),'A') || to_tsvector('simple','IEC 61009: RCBOs. Residual-current circuit breakers incorporating overcurrent protection; distinguish from RCCBs.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('ae185086-7596-55a4-8812-d49b245e7c26','IEC 61439 — Low-voltage switchgear/controlgear assemblies (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 61439','IEC 61439','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 61439: Low-voltage switchgear/controlgear assemblies. Assembly verification family; individual component ratings alone do not establish assembly compliance.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','388782fa7ca6036d7f84664876806250c4b7c357a46c7070930aa8e0690f0832','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('7a022455-0252-5b73-834d-87fe3867fb08','ae185086-7596-55a4-8812-d49b245e7c26','Scope metadata','Scope metadata',0,'IEC 61439: Low-voltage switchgear/controlgear assemblies. Assembly verification family; individual component ratings alone do not establish assembly compliance.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',132,setweight(to_tsvector('simple','IEC 61439 — Low-voltage switchgear/controlgear assemblies (family/scope metadata)'),'A') || to_tsvector('simple','IEC 61439: Low-voltage switchgear/controlgear assemblies. Assembly verification family; individual component ratings alone do not establish assembly compliance.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('15212b23-c360-5220-a495-e57dfc06e399','IEC 60529 — Degrees of protection provided by enclosures (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60529','IEC 60529','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60529: Degrees of protection provided by enclosures. IP classification family. Digits address different hazards; water-jet and immersion ratings are not interchangeable.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','2ac3a675ffdaf574d1218f7e167177a5de6e3c106f00426d19f8fbbf56e855de','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('0c0b81e3-e04e-584b-b13b-fe3b86ba1811','15212b23-c360-5220-a495-e57dfc06e399','Scope metadata','Scope metadata',0,'IEC 60529: Degrees of protection provided by enclosures. IP classification family. Digits address different hazards; water-jet and immersion ratings are not interchangeable.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',136,setweight(to_tsvector('simple','IEC 60529 — Degrees of protection provided by enclosures (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60529: Degrees of protection provided by enclosures. IP classification family. Digits address different hazards; water-jet and immersion ratings are not interchangeable.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('111fd218-4844-5c74-b98e-7e89cfce8479','IEC 60664-1 — Insulation coordination (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60664-1','IEC 60664','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60664-1: Insulation coordination. Insulation coordination, clearance, creepage and solid insulation. Application conditions require the relevant edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','d81340fe85c8bdb1266ff272c0cb34674e6cfab94b17c1d7e9fa5bfa1d5bda26','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('15024c4a-2faf-5a85-ab3b-b509020de838','111fd218-4844-5c74-b98e-7e89cfce8479','Scope metadata','Scope metadata',0,'IEC 60664-1: Insulation coordination. Insulation coordination, clearance, creepage and solid insulation. Application conditions require the relevant edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',131,setweight(to_tsvector('simple','IEC 60664-1 — Insulation coordination (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60664-1: Insulation coordination. Insulation coordination, clearance, creepage and solid insulation. Application conditions require the relevant edition.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('1c3142e4-1de2-5aeb-8de7-bdc14763a359','IEC 61643 — Surge protective devices (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 61643','IEC 61643','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 61643: Surge protective devices. SPD product/application family; select the applicable part for the system and device.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','76c5a28bbf38c213e382248c99be24694cba38bee2f3b2b5438848b70704a5cf','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('4272f7fe-e7a1-5626-b8a7-0f6d4705ec95','1c3142e4-1de2-5aeb-8de7-bdc14763a359','Scope metadata','Scope metadata',0,'IEC 61643: Surge protective devices. SPD product/application family; select the applicable part for the system and device.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',119,setweight(to_tsvector('simple','IEC 61643 — Surge protective devices (family/scope metadata)'),'A') || to_tsvector('simple','IEC 61643: Surge protective devices. SPD product/application family; select the applicable part for the system and device.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('57fc4eec-4fe4-5467-85da-2c4da1930c74','IEC 60204-1 — Electrical equipment of machines (family/scope metadata)','STANDARD','IEC','https://webstore.iec.ch/','IEC','IEC 60204-1','IEC 60204','METADATA_ONLY','Public standard identifiers and original scope summaries only. IEC/EN/EVS standard text is not included. Official catalog link; select the appropriate edition there.','# Scope metadata
IEC 60204-1: Electrical equipment of machines. Machinery electrical equipment scope; distinguish machine requirements from building installation rules.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.','f46c4fe1a64fe8ca2cfdf03dec99bf9c8d1a7a5d1757de79e883600a0e368be0','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('dc00cdcf-6384-5514-9f61-5db520f45954','57fc4eec-4fe4-5467-85da-2c4da1930c74','Scope metadata','Scope metadata',0,'IEC 60204-1: Electrical equipment of machines. Machinery electrical equipment scope; distinguish machine requirements from building installation rules.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.',129,setweight(to_tsvector('simple','IEC 60204-1 — Electrical equipment of machines (family/scope metadata)'),'A') || to_tsvector('simple','IEC 60204-1: Electrical equipment of machines. Machinery electrical equipment scope; distinguish machine requirements from building installation rules.

This is an original catalog description, not standard text. No edition, amendment, effective date or national adoption has been verified. Consult the official catalog and legally available current text before relying on requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('86dfbb12-10cf-5a10-92df-cdf4c2e6ea2e','Schneider Electric — Electrical Installation Guide: asynchronous motors (source directory)','MANUFACTURER_GUIDE','Schneider Electric','https://www.electrical-installation.org/enwiki/Asynchronous_motors','IEC','','','METADATA_ONLY','Source link and original directory summary only. Public access does not automatically grant bulk indexing or redistribution rights.','# Source directory
The guide has sections on asynchronous motors, motor protection functions, motor starter configurations and protection coordination. Retrieve authorized section text and exact manufacturer coordination tables before using application requirements. This entry identifies relevant chapters only; it contains no reproduced guide text.','cca91a3cda2d3c4c3e42046dcedf82bdb4156748b2e976136e68048902433b07','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('92158347-0720-5f12-8284-458d8fae6e50','86dfbb12-10cf-5a10-92df-cdf4c2e6ea2e','Source directory','Source directory',0,'The guide has sections on asynchronous motors, motor protection functions, motor starter configurations and protection coordination. Retrieve authorized section text and exact manufacturer coordination tables before using application requirements. This entry identifies relevant chapters only; it contains no reproduced guide text.',111,setweight(to_tsvector('simple','Schneider Electric — Electrical Installation Guide: asynchronous motors (source directory)'),'A') || to_tsvector('simple','The guide has sections on asynchronous motors, motor protection functions, motor starter configurations and protection coordination. Retrieve authorized section text and exact manufacturer coordination tables before using application requirements. This entry identifies relevant chapters only; it contains no reproduced guide text.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('b18461dc-bdd0-5a83-a0bc-f5db1d846783','TTJA — Electrical installations (source directory)','NATIONAL_REQUIREMENT','Consumer Protection and Technical Regulatory Authority (TTJA)','https://ttja.ee/en/business-client/safety/installations-and-machines/electrical-installations','ESTONIA','','','METADATA_ONLY','Official public source directory with original description; full text not indexed.','# Source directory
Estonian authority guidance concerning electrical installations, safety, operation, inspections and audits. Follow the official links to applicable Estonian requirements. This entry is metadata, not a statement of legal requirements.','ef6d7df003fbfa9d27075d0de3bef5595c33fe33e28a63b8ce93ce302fcc2d06','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('9239bdfc-a539-57c9-8646-5ffdc4aff21b','b18461dc-bdd0-5a83-a0bc-f5db1d846783','Source directory','Source directory',0,'Estonian authority guidance concerning electrical installations, safety, operation, inspections and audits. Follow the official links to applicable Estonian requirements. This entry is metadata, not a statement of legal requirements.',78,setweight(to_tsvector('simple','TTJA — Electrical installations (source directory)'),'A') || to_tsvector('simple','Estonian authority guidance concerning electrical installations, safety, operation, inspections and audits. Follow the official links to applicable Estonian requirements. This entry is metadata, not a statement of legal requirements.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('19c675a4-eef1-5629-a0e3-4e9d8f1b38b8','Low Voltage Directive 2014/35/EU (source metadata)','LAW','European Union — EUR-Lex','https://eur-lex.europa.eu/eli/dir/2014/35/oj/eng','EU','','','METADATA_ONLY','Official EUR-Lex identifier and original description; no legislative clauses indexed.','# Scope metadata
EU Low Voltage Directive 2014/35/EU: electrical equipment safety and placing products on the EU market. Check scope, economic-operator obligations, CE conformity and current consolidated text. This metadata does not establish product compliance.','bcba7ba3600a55b337e61ea3510abd249cf69129e87b2f9413fdebae9c70a9ff','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('3864255b-b7f1-5c4d-8545-ea1b9f881f1b','19c675a4-eef1-5629-a0e3-4e9d8f1b38b8','Scope metadata','Scope metadata',0,'EU Low Voltage Directive 2014/35/EU: electrical equipment safety and placing products on the EU market. Check scope, economic-operator obligations, CE conformity and current consolidated text. This metadata does not establish product compliance.',82,setweight(to_tsvector('simple','Low Voltage Directive 2014/35/EU (source metadata)'),'A') || to_tsvector('simple','EU Low Voltage Directive 2014/35/EU: electrical equipment safety and placing products on the EU market. Check scope, economic-operator obligations, CE conformity and current consolidated text. This metadata does not establish product compliance.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('bf4ae68d-2fe1-5588-a92c-725ae6d7e54f','EMC Directive 2014/30/EU (source metadata)','LAW','European Union — EUR-Lex','https://eur-lex.europa.eu/eli/dir/2014/30/oj/eng','EU','','','METADATA_ONLY','Official EUR-Lex identifier and original description; no legislative clauses indexed.','# Scope metadata
EU EMC Directive 2014/30/EU concerns electromagnetic compatibility of equipment. Check the current consolidated legislation and the distinction between apparatus and fixed installations.','6325b805fd999bfe51f7b9d3160e4c72867f0e873cefbe4a4477b2d3ce7e695c','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('d2aee92a-dde8-5893-9365-41887a067de0','bf4ae68d-2fe1-5588-a92c-725ae6d7e54f','Scope metadata','Scope metadata',0,'EU EMC Directive 2014/30/EU concerns electromagnetic compatibility of equipment. Check the current consolidated legislation and the distinction between apparatus and fixed installations.',62,setweight(to_tsvector('simple','EMC Directive 2014/30/EU (source metadata)'),'A') || to_tsvector('simple','EU EMC Directive 2014/30/EU concerns electromagnetic compatibility of equipment. Check the current consolidated legislation and the distinction between apparatus and fixed installations.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('6263d54d-1fd1-5362-80ec-dd24b57438ff','RoHS Directive 2011/65/EU (source metadata)','LAW','European Union — EUR-Lex','https://eur-lex.europa.eu/eli/dir/2011/65/oj/eng','EU','','','METADATA_ONLY','Official EUR-Lex identifier and original description; no legislative clauses indexed.','# Scope metadata
EU RoHS Directive 2011/65/EU concerns restrictions on certain hazardous substances in electrical and electronic equipment. Check current amendments, product scope and applicable exemptions.','32df35a067cc2250072399bf577b033a2171a7a68f3a0bc67639504c28611760','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('e4af0a78-1bdd-5149-ac4b-c41774575142','6263d54d-1fd1-5362-80ec-dd24b57438ff','Scope metadata','Scope metadata',0,'EU RoHS Directive 2011/65/EU concerns restrictions on certain hazardous substances in electrical and electronic equipment. Check current amendments, product scope and applicable exemptions.',63,setweight(to_tsvector('simple','RoHS Directive 2011/65/EU (source metadata)'),'A') || to_tsvector('simple','EU RoHS Directive 2011/65/EU concerns restrictions on certain hazardous substances in electrical and electronic equipment. Check current amendments, product scope and applicable exemptions.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('21dc26fb-5d92-5b64-b58a-6635cce92ab3','EU Blue Guide 2022 (source metadata)','DESIGN_GUIDE','European Commission — EUR-Lex','https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022XC0629(04)','EU','','','METADATA_ONLY','Official source identifier and original description; no full guide text indexed.','# Scope metadata
The 2022 Blue Guide explains implementation of EU product rules, CE marking, conformity assessment and economic-operator obligations. It is non-binding explanatory guidance, not legislation. Confirm whether subsequent revisions apply.','f13a32806c327417348b05201ee29db3ba530b49e67955a46cbb8f067c989ead','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('9714d09d-bc23-5e69-a0e1-30795e135a5b','21dc26fb-5d92-5b64-b58a-6635cce92ab3','Scope metadata','Scope metadata',0,'The 2022 Blue Guide explains implementation of EU product rules, CE marking, conformity assessment and economic-operator obligations. It is non-binding explanatory guidance, not legislation. Confirm whether subsequent revisions apply.',78,setweight(to_tsvector('simple','EU Blue Guide 2022 (source metadata)'),'A') || to_tsvector('simple','The 2022 Blue Guide explains implementation of EU product rules, CE marking, conformity assessment and economic-operator obligations. It is non-binding explanatory guidance, not legislation. Confirm whether subsequent revisions apply.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('938d5caa-cd25-55c6-8490-9966f374ba99','Lessons In Electric Circuits — Ohm’s law (adapted summary)','THEORY','Tony R. Kuphaldt; summary adapted by E.R.R.O.','https://www.ibiblio.org/kuphaldt/electricCircuits/DC/DC_2.html','INTERNATIONAL','','','OPEN_LICENSE','Adapted summary of Tony R. Kuphaldt, Lessons In Electric Circuits, Volume I, chapter 2; wording shortened and rewritten by E.R.R.O. Original CC BY 4.0: https://creativecommons.org/licenses/by/4.0/ . License confirmed at https://www.ibiblio.org/kuphaldt/electricCircuits/DC/DC_A3.html .','# Ohmic circuits
For an ohmic resistance, voltage equals current multiplied by resistance: V = I × R. Resistance is measured in ohms, voltage in volts and current in amperes. In a steady DC circuit, electrical power is voltage multiplied by current: P = V × I. These circuit relationships do not select a protection device or establish installation compliance.','2073043442743b03dba3ff1a49b551d1dd301a9a26c0034e9f858bf0d0c49f1d','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('25b4970d-8fc6-5519-8299-dd17bc216548','938d5caa-cd25-55c6-8490-9966f374ba99','Ohmic circuits','Ohmic circuits',0,'For an ohmic resistance, voltage equals current multiplied by resistance: V = I × R. Resistance is measured in ohms, voltage in volts and current in amperes. In a steady DC circuit, electrical power is voltage multiplied by current: P = V × I. These circuit relationships do not select a protection device or establish installation compliance.',115,setweight(to_tsvector('simple','Lessons In Electric Circuits — Ohm’s law (adapted summary)'),'A') || to_tsvector('simple','For an ohmic resistance, voltage equals current multiplied by resistance: V = I × R. Resistance is measured in ohms, voltage in volts and current in amperes. In a steady DC circuit, electrical power is voltage multiplied by current: P = V × I. These circuit relationships do not select a protection device or establish installation compliance.'));

INSERT INTO knowledge_document (id,title,source_type,publisher,source_url,jurisdiction,standard_number,standard_family,copyright_status,license_notes,content,source_hash,status,document_version) VALUES ('b9282ad9-9a84-5798-8491-5843b864ded2','Lessons In Electric Circuits — Polyphase AC circuits (adapted summary)','THEORY','Tony R. Kuphaldt; summary adapted by E.R.R.O.','https://www.ibiblio.org/kuphaldt/electricCircuits/AC/AC_10.html','INTERNATIONAL','','','OPEN_LICENSE','Adapted summary of Tony R. Kuphaldt, Lessons In Electric Circuits, Volume II, chapter 10; wording shortened and rewritten by E.R.R.O. Original CC BY 4.0: https://creativecommons.org/licenses/by/4.0/ . See the source volume license appendix. No US wiring rules were imported.','# Three-phase principles
A balanced three-phase system has phase waveforms separated by 120 electrical degrees. Line-to-line voltage and phase voltage are different quantities. For a balanced star connection their magnitudes differ by a factor of square root of three. Star and delta connections have different line/phase current and voltage relationships. Polyphase motor operation and phase rotation depend on these relationships. This is circuit theory; it does not provide a motor protection rating or national installation requirements.','f09de4bba31561a799dba4a1133334f9e024c274084688f41e39d99b8a1bdbee','READY','starter-2026-10-05');

INSERT INTO knowledge_chunk (id,document_id,section_title,section_path,chunk_index,content,token_count,search_vector) VALUES ('4a87821b-fc8e-595f-a866-8c97f4d8d2fc','b9282ad9-9a84-5798-8491-5843b864ded2','Three-phase principles','Three-phase principles',0,'A balanced three-phase system has phase waveforms separated by 120 electrical degrees. Line-to-line voltage and phase voltage are different quantities. For a balanced star connection their magnitudes differ by a factor of square root of three. Star and delta connections have different line/phase current and voltage relationships. Polyphase motor operation and phase rotation depend on these relationships. This is circuit theory; it does not provide a motor protection rating or national installation requirements.',172,setweight(to_tsvector('simple','Lessons In Electric Circuits — Polyphase AC circuits (adapted summary)'),'A') || to_tsvector('simple','A balanced three-phase system has phase waveforms separated by 120 electrical degrees. Line-to-line voltage and phase voltage are different quantities. For a balanced star connection their magnitudes differ by a factor of square root of three. Star and delta connections have different line/phase current and voltage relationships. Polyphase motor operation and phase rotation depend on these relationships. This is circuit theory; it does not provide a motor protection rating or national installation requirements.'));
