import assert from 'node:assert/strict'
import { chromium } from 'playwright'

const base = process.env.ERRO_TEST_URL
const token = process.env.ERRO_TEST_ADMIN_TOKEN
if (!base || !/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base) || !token) throw new Error('Run scripts/verify-browser.sh against its isolated local fixture.')
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage()
page.setDefaultTimeout(20_000)
const errors = []
page.on('pageerror', error => errors.push(error.message))
let importedId
const api = async (path, method = 'GET', body) => {
  const r = await fetch(`${base}/api/admin/knowledge/${path}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) })
  assert.ok(r.ok, `Admin ${method} ${path}: ${r.status}`)
  return r.json().catch(() => null)
}
try {
  await page.goto(base)
  const field = page.getByRole('textbox', { name: 'Message E.R.R.O. AI' })
  const send = page.getByRole('button', { name: 'Send message' })
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `Homepage overflow at ${width}`)
    assert.ok(await field.isVisible(), `Chat immediately available at ${width}`)
    const composer = await field.boundingBox()
    assert.ok(composer.y >= 0 && composer.y + composer.height < 900, `Composer in first viewport at ${width}`)
    if (width !== 768) await page.screenshot({ path: `/tmp/erro-chat-home-${width}.png`, fullPage: true })
  }
  await page.getByRole('button', { name: /Protect a motor/ }).click()
  assert.ok((await field.inputValue()).includes('7.5 kW motor'))
  assert.equal(await page.locator('.message-user').count(), 0, 'Starter prompts are editable before sending')
  await page.getByRole('navigation').getByRole('link', { name: 'About us' }).click()
  await page.getByRole('heading', { name: 'Eric Rand' }).waitFor()
  assert.equal(await field.isVisible(), false)
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth))
  await page.getByRole('navigation').getByRole('link', { name: 'Contact us' }).click()
  await page.getByRole('heading', { name: /Good things start/ }).waitFor()
  assert.equal(await page.getByRole('link', { name: 'eric.rand66@gmail.com' }).getAttribute('href'), 'mailto:eric.rand66@gmail.com')
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth))
  await page.getByRole('navigation').getByRole('link', { name: 'Chat', exact: true }).click()
  assert.ok((await field.inputValue()).includes('7.5 kW motor'), 'Navigation preserves draft')
  await field.fill('I have a 400 V 3-phase 7.5 kW motor, PF 0.82, efficiency 90%, and need protection')
  await send.click()
  await page.getByText('Waiting for a reply…', { exact: true }).waitFor()
  assert.ok(await send.isDisabled())
  await page.getByText('Engineering reply.', { exact: true }).waitFor()
  await page.getByText('Sources (1)', { exact: true }).click()
  assert.ok(await page.locator('.answer-detail a').count() > 0)
  await page.getByText('Calculations (2)', { exact: true }).click()
  await page.getByText(/Estimated motor current: 14\.668/).waitFor()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth))
  await page.locator('.chat-content').screenshot({ path: '/tmp/erro-knowledge-chat.png' })
  await page.getByRole('navigation').getByRole('link', { name: 'About us' }).click()
  await page.getByRole('heading', { name: 'Eric Rand' }).waitFor()
  await page.goBack()
  await page.getByText('Engineering reply.', { exact: true }).waitFor()
  assert.equal(await page.getByRole('navigation').getByRole('link', { name: 'Chat', exact: true }).getAttribute('aria-current'), 'page')
  console.log('PASS: responsive chat, citations, calculations')
  const followup = page.waitForRequest(request => request.url().endsWith('/api/chat') && request.method() === 'POST')
  await field.fill('about 30 meters from the panel')
  await send.click()
  assert.equal((await followup).postDataJSON().problemContext.length, 1)
  await page.waitForFunction(() => document.querySelectorAll('.message-assistant').length === 2)
  await page.getByRole('button', { name: 'New problem', exact: true }).click()
  assert.equal(await page.locator('.message-assistant').count(), 0)
  await field.fill('test-error')
  await send.click()
  await page.getByRole('alert').waitFor()
  assert.equal(await field.inputValue(), 'test-error')
  await field.fill('The prospective fault current is 9 kA and this MCB has 6 kA breaking capacity. Is that okay?')
  await send.click()
  await page.getByText(/The stated combination is unsuitable/).waitFor()
  await page.reload()
  assert.equal(await page.locator('.message-assistant').count(), 0)
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0)
  await page.goto(`${base}/#contact`)
  await page.reload()
  await page.getByRole('heading', { name: /Good things start/ }).waitFor()
  await page.getByRole('navigation').getByRole('link', { name: 'Chat', exact: true }).click()
  await field.waitFor()
  assert.equal(await field.inputValue(), '')

  console.log('PASS: navigation, direct links, draft preservation, follow-up, reset, errors, deterministic failure, refresh')
  await field.fill('test-table')
  await send.click()
  const table = page.getByRole('table')
  await table.waitFor()
  assert.deepEqual(await table.getByRole('columnheader').allTextContents(), ['Observation', 'Engineering meaning'])
  assert.equal(await table.getByRole('row').count(), 4)
  assert.equal(await table.getByRole('cell').count(), 6)
  assert.equal(await table.locator('strong').textContent(), 'Confirm the cross-section.')
  assert.equal(await table.locator('code').textContent(), 'AC|DC')
  assert.equal(await table.getByRole('link').getAttribute('href'), 'https://example.com/reference')
  assert.equal(await page.locator('.message-body pre code').textContent(), '| Literal | Code |\n| --- | --- |\n')
  assert.equal(await page.locator('.message-body > ul > li').count(), 2)
  assert.equal(await page.locator('.message-body img, .message-body script').count(), 0)
  assert.equal(await page.getByText('Image description', { exact: true }).count(), 1)
  assert.equal(await page.evaluate(() => window.tableHtmlExecuted), undefined)
  assert.ok(!(await page.getByText('Unsafe link', { exact: true }).getAttribute('href'))?.startsWith('javascript:'))
  const tableRegion = page.getByRole('region', { name: 'Table in assistant reply' })
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await tableRegion.scrollIntoViewIfNeeded()
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), `Table page overflow at ${width}`)
    if (width < 500) {
      assert.ok(await tableRegion.evaluate(el => el.scrollWidth > el.clientWidth), 'Mobile table scrolls inside its container')
      await tableRegion.evaluate(el => { el.scrollLeft = 0 })
      await tableRegion.focus()
      await page.keyboard.press('ArrowRight')
      await page.waitForFunction(() => document.querySelector('.message-table').scrollLeft > 0)
      await tableRegion.evaluate(el => { el.scrollLeft = 0 })
    }
    if (width === 1440 || width === 390) await page.screenshot({ path: `/tmp/erro-chat-table-${width}.png`, fullPage: true })
  }
  await page.reload()
  assert.equal(await page.getByRole('table').count(), 0)
  console.log('PASS: Markdown table headers/cells, inline formatting, escaped pipes, literal code, safe HTML/URLs, mobile keyboard scrolling, refresh')
  const unauthorized = await fetch(`${base}/api/admin/knowledge/documents`)
  assert.equal(unauthorized.status, 401)
  const encoded = await fetch(`${base}/api/%61dmin/knowledge/documents`)
  assert.equal(encoded.status, 401)
  await page.goto(`${base}/#knowledge`)
  await page.getByLabel('Administrator token').fill(token)
  await page.getByRole('button', { name: 'Unlock knowledge management' }).click()
  await page.getByRole('heading', { name: 'Sources', exact: true }).waitFor()
  console.log('PASS: protected admin unlock')
  assert.equal(await page.locator('.source-list > li').count(), 20)
  await page.getByRole('button', { name: 'Inspect retrieval', exact: true }).click()
  await page.getByText('Retrieval and generation context', { exact: true }).waitFor()
  assert.ok((await page.locator('pre').last().textContent()).includes('MOTOR'))
  await page.getByLabel('Title', { exact: true }).fill('Browser test source')
  await page.getByLabel('Publisher', { exact: true }).fill('Browser test fixture')
  await page.locator('select[name=copyrightStatus]').selectOption('USER_PROVIDED')
  await page.getByLabel('License, attribution and permission notes').fill('Original test fixture; no third-party copyrighted content.')
  await page.getByLabel('Markdown or plain text', { exact: true }).fill('# Browser verification\nMotor protection requires documented coordination. This is a test fixture only.')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Ingest source', exact: true }).click()
  await page.getByRole('heading', { name: 'Browser test source', exact: true }).waitFor()
  importedId = (await api('documents')).find(d => d.title === 'Browser test source').id
  const row = page.locator('.source-list > li').filter({ hasText: 'Browser test source' })
  assert.ok((await row.textContent()).includes('READY'))
  await row.getByRole('button', { name: 'Disable', exact: true }).click()
  await row.getByRole('button', { name: 'Enable', exact: true }).waitFor()
  await row.getByRole('button', { name: 'Enable', exact: true }).click()
  await row.getByRole('button', { name: 'Disable', exact: true }).waitFor()
  await row.getByRole('button', { name: 'Re-index', exact: true }).click()
  await page.getByRole('button', { name: 'Refresh sources' }).waitFor({ state: 'visible' })
  await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(b => b.textContent === 'Refresh sources').disabled)
  await row.getByRole('button', { name: 'Inspect chunks', exact: true }).click()
  await page.getByText('Source inspection', { exact: true }).waitFor()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), 'Admin mobile overflow')
  await page.reload()
  await page.getByRole('button', { name: 'Unlock knowledge management' }).waitFor()
  assert.equal(await page.getByLabel('Administrator token').inputValue(), '')
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0)
  assert.deepEqual(errors, [])
  console.log('PASS: chat, real backend retrieval, citations, calculation display, loading/errors, follow-up/reset/refresh, mobile layouts, admin auth/debug/ingestion/toggles/re-index, no browser persistence')
} finally {
  if (importedId) await api(`documents/${importedId}`, 'DELETE')
  await browser.close()
}
